#!/bin/bash

sudo apt-get update

#Installing g++
sudo apt-get install g++

#Installing cmake
sudo apt install -y cmake

sudo apt install -y make

#wget
sudo apt install -y wget unzip

#git
sudo apt install -y git

#opencv
cd #Move to home

wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip
unzip opencv.zip
mv opencv-4.x opencv

mkdir -p build && cd build

cmake ../opencv

make -j4

sudo make install


#Absl
cd #go home

mkdir Source && cd Source

git clone https://github.com/abseil/abseil-cpp.git

cd abseil-cpp

mkdir build && cd build

cmake -DABSL_BUILD_TESTING=ON -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=14 ..

cmake --build . --target all

make

#grpc

cd # go home

export MY_INSTALL_DIR=$HOME/.local

mkdir -p $MY_INSTALL_DIR

export PATH="$MY_INSTALL_DIR/bin:$PATH"

sudo apt install -y build-essential autoconf libtool pkg-config

git clone --recurse-submodules -b v1.60.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc

cd grpc

mkdir -p cmake/build

pushd cmake/build

cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
      ../..

make -j 4

make install

popd

